# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-14 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_auto_20181111_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCorrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField()),
                ('fromSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_sessions', to='Academics.Session')),
                ('toSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_sessions', to='Academics.Session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='correlation',
            field=models.ManyToManyField(through='Academics.SessionCorrelation', to='Academics.Session'),
        ),
    ]
