# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0004_auto_20181114_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('fromSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conflicts', to='Academics.Session')),
                ('toSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conflicts', to='Academics.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='sessioncorrelation',
            name='fromSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_correlations', to='Academics.Session'),
        ),
        migrations.AlterField(
            model_name='sessioncorrelation',
            name='toSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_correlations', to='Academics.Session'),
        ),
    ]
