# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_auto_20181115_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='correlation',
        ),
        migrations.AddField(
            model_name='session',
            name='conflicts',
            field=models.ManyToManyField(related_name='conflicts_with', through='Academics.SessionConflict', to='Academics.Session'),
        ),
        migrations.AddField(
            model_name='session',
            name='correlations',
            field=models.ManyToManyField(related_name='correlated_with', through='Academics.SessionCorrelation', to='Academics.Session'),
        ),
    ]
