# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-22 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Academics', '0007_auto_20190222_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvedLevel', models.SmallIntegerField(default=0)),
                ('deniedLevel', models.SmallIntegerField(default=0)),
                ('approvedBy', models.ManyToManyField(related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('deniedBy', models.ManyToManyField(related_name='denied_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('sectionStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.SectionStudent')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approverLists', models.ManyToManyField(to='Academics.ApproverList')),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academics.College')),
            ],
        ),
        migrations.AlterModelTable(
            name='sectionstudentparent',
            table='ENROLL_VW',
        ),
    ]
