# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0012_auto_20190224_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minstrm', models.CharField(db_column=b'MINSTRM', max_length=4)),
                ('maxstrm', models.CharField(db_column=b'MAXSTRM', max_length=4)),
                ('subject', models.CharField(db_column=b'SUBJECT', max_length=8)),
                ('catalog_nbr', models.CharField(db_column=b'CATALOG_NBR', max_length=10)),
                ('acad_group', models.CharField(db_column=b'ACAD_GROUP', max_length=5)),
                ('acad_org', models.CharField(db_column=b'ACAD_ORG', max_length=10)),
                ('crse_id', models.CharField(db_column=b'CRSE_ID', max_length=6)),
                ('course_title_long', models.CharField(db_column=b'COURSE_TITLE_LONG', max_length=100)),
                ('units_acad_prog', models.SmallIntegerField(db_column=b'UNITS_ACAD_PROG')),
                ('crse_contact_hrs', models.SmallIntegerField(db_column=b'CRSE_CONTACT_HRS')),
                ('descrlong', models.CharField(db_column=b'DESCRLONG', max_length=4000)),
                ('effdt', models.DateField(db_column=b'EFFDT')),
            ],
            options={
                'db_table': 'COURSE_VW',
                'managed': False,
            },
        ),
    ]
