# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-03 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0013_courseparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
