# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-04 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0016_program_aoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'Sabbatical', b'Sabbatical'), (b'LWDIP', b'Leave With Difference in Pay'), (b'LWOP', b'Leave Without Pay'), (b'FERP', b'Faculty Early Retirement Program')], max_length=60)),
                ('timeBase', models.DecimalField(decimal_places=2, max_digits=3)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Term')),
            ],
        ),
        migrations.AlterModelTable(
            name='sectionparent',
            table='SECTION_VW',
        ),
    ]
