# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-09 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0017_auto_20190404_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='FERP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('FTE', models.FloatField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='leave',
            name='term',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='timeBase',
        ),
        migrations.AddField(
            model_name='leave',
            name='FTE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='effectiveDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[(b'Sabbatical', b'Sabbatical'), (b'LWDIP', b'Leave With Difference in Pay'), (b'LWOP', b'Leave Without Pay')], max_length=60),
        ),
    ]
