# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-17 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0018_auto_20190409_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('nickname', models.CharField(blank=True, max_length=8)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('acadGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.AcademicGroup')),
                ('acadOrg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.AcademicOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[(b'', b''), (b'chair', b'Chair'), (b'facilitator', b'Facilitator'), (b'recorder', b'Recorder'), (b'ex-officio', b'Ex-Officio')], max_length=32)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Committee')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteePersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, through='Academics.CommitteePerson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together=set([('acadOrg', 'acadGroup', 'name')]),
        ),
    ]
