# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0019_auto_20190417_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeperson',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.CommitteePersonRole'),
        ),
    ]
