# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-17 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0020_auto_20190417_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='size',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='termYears',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committeeperson',
            name='termEnd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committeeperson',
            name='termStart',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
