# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-18 01:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0021_auto_20190417_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='position',
        ),
        migrations.RemoveField(
            model_name='position',
            name='departmentCode',
        ),
        migrations.RemoveField(
            model_name='position',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='position',
            name='positionCode',
        ),
        migrations.AddField(
            model_name='position',
            name='actionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='apptEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.CharField(default='Placeholder', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='departmentID',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='effectiveDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='firstHireDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='fullTimeCompRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='grade',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='jobCode',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='monthlySalary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='payStatus',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='positionNumber',
            field=models.CharField(default='00000000', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='timeBase',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
