# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-11 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0023_auto_20190418_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='acad_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
