# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-11 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0024_academicgroup_acad_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicorganization',
            name='acad_org',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
