# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-11 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0025_academicorganization_acad_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermParent',
            fields=[
                ('id', models.IntegerField(db_column=b'ID', primary_key=True, serialize=False)),
                ('strm', models.CharField(db_column=b'STRM', max_length=4)),
                ('descr', models.CharField(db_column=b'DESCR', max_length=30)),
                ('descrshort', models.CharField(db_column=b'DESCRSHORT', max_length=10)),
                ('term_begin_dt', models.DateField(db_column=b'TERM_BEGIN_DT')),
                ('term_end_dt', models.DateField(db_column=b'TERM_END_DT')),
                ('session_code', models.CharField(db_column=b'SESSION_CODE', max_length=3)),
                ('weeks_of_instruct', models.IntegerField(db_column=b'WEEKS_OF_INSTRUCT')),
                ('term_category', models.CharField(db_column=b'TERM_CATEGORY', max_length=1)),
                ('acad_year', models.CharField(db_column=b'ACAD_YEAR', max_length=4)),
            ],
            options={
                'db_table': 'CMSCOMMON.SFO_TERM_TBL',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='term',
            name='academicYear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='descr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='descrshort',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='sessionCode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='termCategory',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='weeksOfInstruct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
