# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-11 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0027_auto_20190711_1822'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='termparent',
            table='"CMSCOMMON"."SFO_TERM_TBL"',
        ),
    ]
