# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-25 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0028_auto_20190711_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroupParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_deptid', models.CharField(db_column=b'DEPTID', max_length=4)),
                ('college_name', models.CharField(db_column=b'COLLEGE_NAME', max_length=100)),
                ('acad_group', models.CharField(db_column=b'ACAD_GROUP', max_length=25)),
                ('college_nickname', models.CharField(db_column=b'COLLEGE_NICKNAME', max_length=4)),
            ],
            options={
                'db_table': 'COLLEGE_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAttributeParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crse_id', models.CharField(db_column=b'CRSE_ID', max_length=6)),
                ('crse_offer_nbr', models.IntegerField(db_column=b'CRSE_OFFER_NBR')),
                ('strm', models.CharField(db_column=b'STRM', max_length=4)),
                ('session_code', models.CharField(db_column=b'SESSION_CODE', max_length=3)),
                ('class_section', models.CharField(db_column=b'CLASS_SECTION', max_length=4)),
                ('crse_attr', models.CharField(db_column=b'CRSE_ATTR', max_length=4)),
                ('crse_attr_value', models.CharField(db_column=b'CRSE_ATTR_VALUE', max_length=10)),
            ],
            options={
                'db_table': '"CMSCOMMON"."SFO_CLASS_ATTRIBUTE"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAttributeValueParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crse_attr', models.CharField(db_column=b'CRSE_ATTR', max_length=4)),
                ('effdt', models.DateTimeField(db_column=b'EFFDT')),
                ('crse_attr_value', models.CharField(db_column=b'CRSE_ATTR_VALUE', max_length=10)),
                ('descr', models.CharField(db_column=b'DESCR', max_length=30)),
                ('descrformal', models.CharField(db_column=b'DESCRFORMAL', max_length=50)),
            ],
            options={
                'db_table': '"CMSCOMMON"."SFO_CRSE_ATTR_VALUE"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDefinitionParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crse_id', models.CharField(db_column=b'CRSE_ID', max_length=6)),
                ('effdt', models.DateTimeField(db_column=b'EFFDT')),
                ('eff_status', models.CharField(db_column=b'EFF_STATUS', max_length=1)),
                ('descr', models.CharField(db_column=b'DESCR', max_length=30)),
                ('course_title_long', models.CharField(db_column=b'COURSE_TITLE_LONG', max_length=100)),
                ('units_acad_prog', models.SmallIntegerField(db_column=b'UNITS_ACAD_PROG')),
                ('crse_contact_hrs', models.SmallIntegerField(db_column=b'CRSE_CONTACT_HRS')),
                ('descrlong', models.CharField(db_column=b'DESCRLONG', max_length=4000)),
                ('fees_exist', models.CharField(db_column=b'FEES_EXIST', max_length=1)),
            ],
            options={
                'db_table': '"CMSCOMMON"."SFO_CRSE_CATALOG"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseOfferParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_column=b'SUBJECT', max_length=8)),
                ('catalog_nbr', models.CharField(db_column=b'CATALOG_NBR', max_length=10)),
                ('crse_id', models.CharField(db_column=b'CRSE_ID', max_length=6)),
                ('effdt', models.DateTimeField(db_column=b'EFFDT')),
                ('crse_offer_nbr', models.IntegerField(db_column=b'CRSE_OFFER_NBR')),
                ('acad_group', models.CharField(db_column=b'ACAD_GROUP', max_length=5)),
                ('acad_org', models.CharField(db_column=b'ACAD_ORG', max_length=10)),
                ('acad_career', models.CharField(db_column=b'ACAD_CAREER', max_length=4)),
            ],
            options={
                'db_table': '"CMSCOMMON"."SFO_CRSE_OFFER"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeprecatedSectionParent',
            fields=[
                ('id', models.IntegerField(db_column=b'ID', primary_key=True, serialize=False)),
                ('strm', models.CharField(db_column=b'STRM', max_length=4)),
                ('classNumber', models.IntegerField(db_column=b'CLASS_NBR')),
                ('courseID', models.CharField(db_column=b'CRSE_ID', max_length=6)),
                ('subject', models.CharField(db_column=b'SUBJECT', max_length=8)),
                ('catalogNumber', models.CharField(db_column=b'CATALOG_NBR', max_length=10)),
                ('classSection', models.CharField(db_column=b'CLASS_SECTION', max_length=4)),
                ('courseDescription', models.CharField(db_column=b'DESCR', max_length=30)),
                ('units', models.IntegerField(db_column=b'UNITS_ACAD_PROG')),
                ('courseType', models.CharField(db_column=b'SSR_COMPONENT', max_length=3)),
                ('meetDays', models.CharField(db_column=b'MEETING_DAYS', max_length=4)),
                ('startTime', models.CharField(db_column=b'START_TIME', max_length=5)),
                ('endTime', models.CharField(db_column=b'END_TIME', max_length=5)),
                ('startDate', models.CharField(db_column=b'START_DATE', max_length=11)),
                ('endDate', models.CharField(db_column=b'END_DATE', max_length=11)),
                ('building', models.CharField(db_column=b'BLDG_CD', max_length=10)),
                ('room', models.CharField(db_column=b'ROOM', max_length=10)),
                ('enrollCap', models.IntegerField(db_column=b'ENRL_CAP')),
                ('waitCap', models.IntegerField(db_column=b'WAIT_CAP')),
                ('instructorID', models.CharField(db_column=b'EMPLID', max_length=9)),
                ('instructorFirstName', models.CharField(db_column=b'FIRST_NAME', max_length=30)),
                ('instructorLastName', models.CharField(db_column=b'LAST_NAME', max_length=30)),
                ('instructorEmail', models.CharField(db_column=b'EMAIL_ADDR', max_length=40)),
                ('enrollCount', models.IntegerField(db_column=b'ENRL_TOT')),
                ('waitCount', models.IntegerField(db_column=b'WAIT_TOT')),
                ('enrollingStatus', models.CharField(db_column=b'ENRL_STAT', max_length=1)),
                ('classStatus', models.CharField(db_column=b'CLASS_STAT', max_length=1)),
                ('classType', models.CharField(db_column=b'CLASS_TYPE', max_length=1)),
                ('associatedClass', models.IntegerField(db_column=b'ASSOCIATED_CLASS')),
                ('schedulePrint', models.CharField(db_column=b'SCHEDULE_PRINT', max_length=1)),
                ('acadOrg', models.CharField(db_column=b'ACAD_ORG', max_length=10)),
                ('acadCareer', models.CharField(db_column=b'ACAD_CAREER', max_length=4)),
                ('acadGroup', models.CharField(db_column=b'ACAD_GROUP', max_length=5)),
                ('institution', models.CharField(db_column=b'INSTITUTION', max_length=5)),
                ('campus', models.CharField(db_column=b'CAMPUS', max_length=5)),
                ('campusEventNumber', models.CharField(db_column=b'CAMPUS_EVENT_NBR', max_length=9)),
                ('combinedSection', models.CharField(db_column=b'COMBINED_SECTION', max_length=1)),
                ('sessionCode', models.CharField(db_column=b'SESSION_CODE', max_length=3)),
            ],
            options={
                'db_table': 'SECTION_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialDepartmentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptid', models.CharField(db_column=b'DEPTID', max_length=20)),
                ('dept_name', models.CharField(db_column=b'DEPT_NAME', max_length=30)),
                ('college_deptid', models.CharField(db_column=b'COLLEGE_DEPTID', max_length=20)),
                ('college_name', models.CharField(db_column=b'COLLEGE_NAME', max_length=30)),
                ('cabinet_deptid', models.CharField(db_column=b'CABINET_DEPTID', max_length=20)),
                ('cabinet_name', models.CharField(db_column=b'CABINET_NAME', max_length=30)),
                ('cfs_dept_name', models.CharField(db_column=b'CFS_DEPT_NAME', max_length=100)),
                ('acad_org', models.CharField(db_column=b'ACAD_ORG', max_length=25)),
                ('acad_group', models.CharField(db_column=b'ACAD_GROUP', max_length=25)),
            ],
            options={
                'db_table': 'DEPARTMENT_HIERARCHY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(blank=True, max_length=30)),
                ('years', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=6)),
                ('effectiveDate', models.DateTimeField()),
                ('effectiveStatus', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('units', models.SmallIntegerField()),
                ('contactHours', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('enrollCap', models.SmallIntegerField()),
                ('enrolled', models.SmallIntegerField()),
                ('waitlistCap', models.SmallIntegerField()),
                ('waitlisted', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptID', models.CharField(max_length=4)),
                ('deptName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SectionInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('role', models.CharField(blank=True, max_length=4, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('wtu', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('schedulePrint', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CourseType',
            new_name='Component',
        ),
        migrations.RenameField(
            model_name='academicgroup',
            old_name='description',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='academicgroup',
            old_name='acad_group',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='enrollingStatus',
            new_name='enrollStatus',
        ),
        migrations.RemoveField(
            model_name='academicorganization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='contactHours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semestersOffered',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='units',
        ),
        migrations.RemoveField(
            model_name='course',
            name='yearsOffered',
        ),
        migrations.RemoveField(
            model_name='section',
            name='courseType',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.AddField(
            model_name='academicorganization',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='academicorganization',
            name='acad_org',
            field=models.CharField(max_length=10, blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='courseparent',
            table='SFO_CRSE_CATALOG_EFF',
        ),
        migrations.AlterModelTable(
            name='sectionparent',
            table='SFO_CS_OSB1_VW',
        ),
        migrations.AddField(
            model_name='sectioninstructor',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Section'),
        ),
        migrations.AddField(
            model_name='enrollmentsnapshot',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Section'),
        ),
        migrations.AddField(
            model_name='coursedefinition',
            name='components',
            field=models.ManyToManyField(blank=True, through='Academics.CourseComponent', to='Academics.Component'),
        ),
        migrations.AddField(
            model_name='coursecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Component'),
        ),
        migrations.AddField(
            model_name='coursecomponent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.CourseDefinition'),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='financialDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.FinancialDepartment'),
        ),
        migrations.AddField(
            model_name='academicorganization',
            name='financialDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.FinancialDepartment'),
        ),
        migrations.AddField(
            model_name='course',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='Academics.CourseAttribute'),
        ),
        migrations.AddField(
            model_name='course',
            name='cadence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.Cadence'),
        ),
        migrations.AddField(
            model_name='course',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.CourseDefinition'),
        ),
        migrations.AddField(
            model_name='section',
            name='courseComponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.CourseComponent'),
        ),
        migrations.AddField(
            model_name='section',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='sections_as_instructor', through='Academics.SectionInstructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coursedefinition',
            unique_together=set([('courseID', 'effectiveDate')]),
        ),
    ]
