# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 00:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicorganization',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='academic_orgs_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='college',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='colleges_is_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='departments_is_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='departments_is_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
