# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-29 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unitsAcadProg',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
