# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='financialdepartment',
            name='cabinet_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='financialdepartment',
            name='college_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='financialdepartment',
            name='deptName',
            field=models.CharField(max_length=60),
        ),
    ]
