# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_auto_20171011_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='academic_groups_as_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
