# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-28 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_auto_20191027_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicOrganizationParent',
            fields=[
                ('acad_org', models.CharField(db_column=b'ACAD_ORG', max_length=10, primary_key=True, serialize=False)),
                ('deptID', models.CharField(db_column=b'DEPTID', max_length=20)),
                ('deptName', models.CharField(db_column=b'DEPT_NAME', max_length=30)),
                ('acad_group', models.CharField(db_column=b'ACAD_GROUP', max_length=3)),
            ],
            options={
                'db_table': 'DEPARTMENT_VW',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='academicorganization',
            name='academicGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.AcademicGroup'),
        ),
        migrations.AlterModelTable(
            name='financialdepartmentparent',
            table='DEPARTMENT_HIERARCHY_VW',
        ),
    ]
