# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-11 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_auto_20181111_2100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('session', 'number', 'classStatus')]),
        ),
    ]
