# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_auto_20171011_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='academicGroup',
        ),
    ]
