# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-30 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0004_auto_20191031_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Degree')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.Student')),
            ],
        ),
        migrations.CreateModel(
            name='GradingBasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[(b'OPT', b'Plus/Minus Letter or CR/NC'), (b'GRD', b'Plus/Minus Letter'), (b'CNC', b'Credit / No-Credit'), (b'SFQ', b'Plus/Minus ABC/NC'), (b'SFW', b'ABC/NC'), (b'SFJ', b'Plus/Minus AB/NC'), (b'SFG', b'SFG: Grad supervision, allows RP'), (b'SFI', b'SFI: Grad supervision, allows RP'), (b'CEU', b'CEL'), (b'NOG', b'Non graded (culminating experience)'), (b'NON', b'Non-graded section of multisection class'), (b'ADM', b'Administratively Determined'), (b'AUD', b'Audit')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='gradingBasis',
            field=models.ManyToManyField(blank=True, to='Academics.GradingBasis'),
        ),
    ]
