# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-22 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0006_auto_20181115_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kfactor',
            old_name='maxCSNumber',
            new_name='CSNumber',
        ),
        migrations.RemoveField(
            model_name='kfactor',
            name='minCSNumber',
        ),
    ]
