# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0008_auto_20190222_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='approvedLevel',
            new_name='approvalLevel',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='deniedLevel',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.NullBooleanField(choices=[(True, b'APPROVED'), (None, b'WAITING'), (False, b'DENIED')], default=None),
        ),
        migrations.AddField(
            model_name='withdrawalpreferences',
            name='denierLists',
            field=models.ManyToManyField(related_name='withdrawal_denier_for', to='Academics.ApproverList'),
        ),
        migrations.AlterField(
            model_name='withdrawalpreferences',
            name='approverLists',
            field=models.ManyToManyField(related_name='withdrawal_approver_for', to='Academics.ApproverList'),
        ),
    ]
