# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0009_auto_20180114_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='effectiveDate',
            new_name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='description',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='id',
        ),
        migrations.AddField(
            model_name='degree',
            name='academicPlan',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='dateModified',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
