# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0010_auto_20180114_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='degree',
            name='dateModified',
            field=models.DateTimeField(),
        ),
    ]
