# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0011_auto_20180114_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='academicOrganization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.AcademicOrganization'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='dateModified',
            field=models.DateTimeField(null=True),
        ),
    ]
