# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0012_auto_20180114_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicorganization',
            name='description',
        ),
        migrations.AlterField(
            model_name='academicorganization',
            name='databaseColumnName',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='academicorganization',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
