# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0013_auto_20180114_0738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='degreestudentparent',
            table='DEGREE_STUDENT',
        ),
    ]
