# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0014_auto_20180114_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTAParent',
            fields=[
                ('emplid', models.CharField(db_column=b'EMPLID', max_length=11, primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column=b'FIRST_NAME', max_length=30)),
                ('lastName', models.CharField(db_column=b'LAST_NAME', max_length=30)),
                ('emailAddress', models.CharField(db_column=b'EMAIL_ADDR', max_length=30)),
                ('lastRegisteredTerm', models.CharField(db_column=b'STRM', max_length=4)),
                ('cumulativeGPA', models.DecimalField(db_column=b'CUM_GPA', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'GTA',
                'managed': False,
            },
        ),
    ]
