# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0015_gtaparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTA',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Academics.Student')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'GTA',
                'verbose_name_plural': 'GTAs',
            },
            bases=('Academics.student',),
        ),
    ]
