# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-03 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0015_course_contacthours'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='aoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs_is_aoc', to=settings.AUTH_USER_MODEL),
        ),
    ]
