# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0016_gta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeParent',
            fields=[
                ('emplid', models.CharField(db_column=b'EMPLID', max_length=11, primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column=b'FIRST_NAME', max_length=30)),
                ('lastName', models.CharField(db_column=b'LAST_NAME', max_length=30)),
                ('emailAddress', models.CharField(db_column=b'EMAIL_ADDR', max_length=30)),
                ('jobCode', models.CharField(db_column=b'JOB_CODE', max_length=128)),
                ('jobDescription', models.CharField(db_column=b'JOB_DESCRIPTION', max_length=128)),
                ('jobAbbreviation', models.CharField(db_column=b'JOB_ABBR', max_length=128)),
                ('jobFunction', models.CharField(db_column=b'JOB_FUNCTION', max_length=128)),
                ('jobTitle', models.CharField(db_column=b'JOB_TITLE', max_length=128)),
                ('jobGrade', models.CharField(db_column=b'JOB_GRADE', max_length=128)),
            ],
            options={
                'db_table': 'EMPLOYEE',
                'managed': False,
            },
        ),
    ]
