# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0017_employeeparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(to='Academics.Course')),
                ('subjects', models.ManyToManyField(to='Academics.Subject')),
            ],
            options={
                'verbose_name': 'lecturer',
                'verbose_name_plural': 'lecturers',
            },
            bases=('Academics.person',),
        ),
    ]
